/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    screens: {
      '3xs': '200px',
      '2xs': '250px',
      'xs': '300px',
      'sm': '380px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        // uppercase: component-object-modifier
        // uppercase: basic
        'background': 'var(--background)',
        'link': 'var(--link)',
        'folder-icon': 'var(--folder-icon)',
        'course-icon': 'var(--course-icon)',
        'article-icon': 'var(--article-icon)',
        'blockquote': 'var(--blockquote)',
        'unhighlighted-code': 'var(--unhighlighted-code)',
        'border-subtle': 'var(--border-subtle)',
        'border-strong': 'var(--border-strong)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-placeholder': 'var(--text-placeholder)',
        'articleh1': 'var(--articleh1)',
        'articleh2': 'var(--articleh2)',
        'text-emph': 'var(--text-emph)',
        'button': 'var(--button)',
        'button-hover': 'var(--button-hover)',
        'linkanchor': 'var(--linkanchor)',

        'Filetree-text-current': 'var(--Filetree-text-current)',
        'Filetree-current': 'var(--Filetree-current)',
        'Filetree-hover': 'var(--Filetree-hover)',
        'Filetree-chevron': 'var(--Filetree-chevron)',
        'Filetree-chevron-hover': 'var(--Filetree-chevron-hover)',
        'Filetree-chevron-current': 'var(--Filetree-chevron-current)',
        'Filetree-chevron-current-hover': 'var(--Filetree-chevron-current-hover)',
        'Filetree-pipe': 'var(--Filetree-pipe)',
        'Filetree-pipe-current': 'var(--Filetree-pipe-current)',
        'Mobiletopbar': 'var(--Mobiletopbar)',
        'Searchbar': 'var(--Searchbar)',
        'Searchbar-hover': 'var(--Searchbar-hover)',
        'Searchbar-ring-hover': 'var(--Searchbar-ring-hover)',
        'Searchpopup-result': 'var(--Searchpopup-result)',
        'Searchpopup-result-selected': 'var(--Searchpopup-result-selected)',
        'Searchpopup-arrow-selected': 'var(--Searchpopup-arrow-selected)',
        'Searchpopup-highlight-dir': 'var(--Searchpopup-highlight-dir)',
        'Searchpopup-highlight-title': 'var(--Searchpopup-highlight-title)',
        'Searchpopup-highlight-content': 'var(--Searchpopup-highlight-content)',
        'Table-bar': 'var(--Table-bar)',
        'Table-bartext': 'var(--Table-bartext)',
        'Table-rows': 'var(--Table-rows)',
        'Popup-overlay': 'var(--Popup-overlay)',
        'Copybutton-icon': 'var(--Copybutton-icon)',
        'Spoiler-accent': 'var(--Spoiler-accent)',
        'Changelog-dates': 'var(--Changelog-dates)',
        'Changelog-titles': 'var(--Changelog-titles)',
        'Incompletemsg': 'var(--Incompletemsg)',
        'Math-accent-thm': 'var(--Math-accent-thm)',
        'Math-accent-proof': 'var(--Math-accent-proof)',
        'Math-accent-defn': 'var(--Math-accent-defn)',
        'Math-accent-example': 'var(--Math-accent-example)',
        'Math-accent-lemma': 'var(--Math-accent-lemma)',
        'Codeblock-bg': 'var(--Codeblock-bg)',
        'Themeselect-topbar': 'var(--Themeselect-topbar)',
        'Themeselect-selected': 'var(--Themeselect-selected)',
        'Themeselect-text-selected': 'var(--Themeselect-text-selected)',
        'Themeselect-hover': 'var(--Themeselect-hover)',
        'Scrollshadow-cover': 'var(--Scrollshadow-cover)',
        'Scrollshadow-blockquote-cover': 'var(--Scrollshadow-blockquote-cover)',
        'Scrollshadow-shadow': 'var(--Scrollshadow-shadow)',
        'Svg-text' : 'var(--Svg-text)',
        'Svg-gray' : 'var(--Svg-gray)',
        'Svg-text-highlight' : 'var(--Svg-text-highlight)',
        'Svg-line-highlight-1' : 'var(--Svg-line-highlight-1)',
        'Svg-line-highlight-2' : 'var(--Svg-line-highlight-2)',
        'Svg-fill-highlight-1' : 'var(--Svg-fill-highlight-1)',
        'Svg-fill-highlight-2' : 'var(--Svg-fill-highlight-2)',
        'Svg-fill-highlight-3' : 'var(--Svg-fill-highlight-3)',
      },
      fontFamily: {
        'lato' : ['var(--font-lato)', 'arial'],
        'space' : ['var(--font-space)', 'arial'],
        'pangolin' : ['var(--font-pangolin)', 'arial'],
        'fira' : ['var(--font-fira)', 'monospace'],
      },
    },
  },
};
