/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    screens: {
      '2xs': '200px',
      'xs': '270px',
      'sm': '380px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        'background': 'var(--background)',
        'background-hover': 'var(--background-hover)',
        'background-hover-hover': 'var(--background-hover-hover)',
        'background-inverse': 'var(--background-inverse)',
        'background-inverse-hover': 'var(--background-inverse-hover)',
        'top-bar-mobile': 'var(--top-bar-mobile)',
        'layer': 'var(--layer)',
        'layer-hover': 'var(--layer-hover)',
        'field': 'var(--field)',
        'field-hover': 'var(--field-hover)',
        'blockquote': 'var(--blockquote)',
        'unhighlighted-code': 'var(--unhighlighted-code)',
        'border-subtle': 'var(--border-subtle)',
        'border-subtle-selected': 'var(--border-subtle-selected)',
        'border-strong': 'var(--border-strong)',
        'border-inverse': 'var(--border-inverse)',
        'highlight-subtle': 'var(--highlight-subtle)',
        'highlight-strong': 'var(--highlight-strong)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-placeholder': 'var(--text-placeholder)',
        'text-inverse': 'var(--text-inverse)',
        'focus': 'var(--focus)',
        'link': 'var(--link)',
        'folder-icon': 'var(--folder-icon)',
        'course-icon': 'var(--course-icon)',
        'overlay': 'var(--overlay)',
      },
      fontFamily: {
        'text' : ['var(--font-text)'],
        'code' : ['var(--font-code)'],
      },
    },
  },
};
